kind: ethereum/contract
name: GuildAppTemplate
network:
source:
  abi: GuildApp
mapping:
  kind: ethereum/events
  apiVersion: 0.0.3
  language: wasm/assemblyscript
  file: ./src/guild-app-mapping.ts
  entities:
    - Guild
    - GuildSubscription
    - Payment
  abis:
    - name: GuildApp
      file: ./abis/GuildApp.json
  eventHandlers:
    - event: "InitializedGuild(address,address,uint256,uint256,(string,string,string,string))"
      handler: handleCreatedGuild
    - event: "UpdatedMetadata(string)"
      handler: handleUpdatedMetadata
    - event: "PausedGuild(bool)"
      handler: handlePausedGuild
    - event: "SubscriptionPriceChanged(address,uint256)"
      handler: handleUpdatedPaymentInfo
    - event: "NewSubscription(address,uint256,uint256,uint256,bytes)"
      handler: handleNewSubcription
    - event: "RenewSubscription(address,uint256,uint256,uint256,bytes)"
      handler: handleRenewSubcription
    - event: "Unsubscribed(uint256)"
      handler: handleUnsubscription
    - event: "Withdraw(address,address,uint256)"
      handler: handleWithdraw
    - event: "Transfer(indexed address,indexed address,indexed uint256)"
      handler: handleSubTransfer